// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: credentialProfiles.sql

package dbgen

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCredentialProfile = `-- name: CreateCredentialProfile :one
INSERT INTO credential_profiles (
    name,
    description,
    protocol,
    payload
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, name, description, protocol, payload, created_at, updated_at
`

type CreateCredentialProfileParams struct {
	Name        string          `json:"name"`
	Description pgtype.Text     `json:"description"`
	Protocol    string          `json:"protocol"`
	Payload     json.RawMessage `json:"payload"`
}

func (q *Queries) CreateCredentialProfile(ctx context.Context, arg CreateCredentialProfileParams) (CredentialProfile, error) {
	row := q.db.QueryRow(ctx, createCredentialProfile,
		arg.Name,
		arg.Description,
		arg.Protocol,
		arg.Payload,
	)
	var i CredentialProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Protocol,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCredentialProfile = `-- name: DeleteCredentialProfile :exec
DELETE FROM credential_profiles
WHERE id = $1
`

func (q *Queries) DeleteCredentialProfile(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCredentialProfile, id)
	return err
}

const getCredentialProfile = `-- name: GetCredentialProfile :one
SELECT id, name, description, protocol, payload, created_at, updated_at FROM credential_profiles
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCredentialProfile(ctx context.Context, id int64) (CredentialProfile, error) {
	row := q.db.QueryRow(ctx, getCredentialProfile, id)
	var i CredentialProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Protocol,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCredentialProfiles = `-- name: ListCredentialProfiles :many
SELECT id, name, description, protocol, payload, created_at, updated_at FROM credential_profiles
ORDER BY name
`

func (q *Queries) ListCredentialProfiles(ctx context.Context) ([]CredentialProfile, error) {
	rows, err := q.db.Query(ctx, listCredentialProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CredentialProfile
	for rows.Next() {
		var i CredentialProfile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Protocol,
			&i.Payload,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCredentialProfile = `-- name: UpdateCredentialProfile :one
UPDATE credential_profiles
SET 
    name = $2,
    description = $3,
    protocol = $4,
    payload = $5,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, description, protocol, payload, created_at, updated_at
`

type UpdateCredentialProfileParams struct {
	ID          int64           `json:"id"`
	Name        string          `json:"name"`
	Description pgtype.Text     `json:"description"`
	Protocol    string          `json:"protocol"`
	Payload     json.RawMessage `json:"payload"`
}

func (q *Queries) UpdateCredentialProfile(ctx context.Context, arg UpdateCredentialProfileParams) (CredentialProfile, error) {
	row := q.db.QueryRow(ctx, updateCredentialProfile,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Protocol,
		arg.Payload,
	)
	var i CredentialProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Protocol,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
