// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: discoveredDevices.sql

package dbgen

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearDiscoveredDevices = `-- name: ClearDiscoveredDevices :exec
DELETE FROM discovered_devices
WHERE discovery_profile_id = $1
`

func (q *Queries) ClearDiscoveredDevices(ctx context.Context, discoveryProfileID pgtype.Int8) error {
	_, err := q.db.Exec(ctx, clearDiscoveredDevices, discoveryProfileID)
	return err
}

const createDiscoveredDevice = `-- name: CreateDiscoveredDevice :one
INSERT INTO discovered_devices (
    discovery_profile_id, ip_address, port, status
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, discovery_profile_id, ip_address, port, status, created_at, updated_at
`

type CreateDiscoveredDeviceParams struct {
	DiscoveryProfileID pgtype.Int8 `json:"discovery_profile_id"`
	IpAddress          netip.Addr  `json:"ip_address"`
	Port               int32       `json:"port"`
	Status             pgtype.Text `json:"status"`
}

func (q *Queries) CreateDiscoveredDevice(ctx context.Context, arg CreateDiscoveredDeviceParams) (DiscoveredDevice, error) {
	row := q.db.QueryRow(ctx, createDiscoveredDevice,
		arg.DiscoveryProfileID,
		arg.IpAddress,
		arg.Port,
		arg.Status,
	)
	var i DiscoveredDevice
	err := row.Scan(
		&i.ID,
		&i.DiscoveryProfileID,
		&i.IpAddress,
		&i.Port,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDiscoveredDevice = `-- name: DeleteDiscoveredDevice :exec
DELETE FROM discovered_devices
WHERE id = $1
`

func (q *Queries) DeleteDiscoveredDevice(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteDiscoveredDevice, id)
	return err
}

const getDiscoveredDevice = `-- name: GetDiscoveredDevice :one
SELECT id, discovery_profile_id, ip_address, port, status, created_at, updated_at FROM discovered_devices
WHERE id = $1
`

func (q *Queries) GetDiscoveredDevice(ctx context.Context, id int64) (DiscoveredDevice, error) {
	row := q.db.QueryRow(ctx, getDiscoveredDevice, id)
	var i DiscoveredDevice
	err := row.Scan(
		&i.ID,
		&i.DiscoveryProfileID,
		&i.IpAddress,
		&i.Port,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllDiscoveredDevices = `-- name: ListAllDiscoveredDevices :many
SELECT id, discovery_profile_id, ip_address, port, status, created_at, updated_at FROM discovered_devices
ORDER BY created_at DESC
`

func (q *Queries) ListAllDiscoveredDevices(ctx context.Context) ([]DiscoveredDevice, error) {
	rows, err := q.db.Query(ctx, listAllDiscoveredDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscoveredDevice
	for rows.Next() {
		var i DiscoveredDevice
		if err := rows.Scan(
			&i.ID,
			&i.DiscoveryProfileID,
			&i.IpAddress,
			&i.Port,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiscoveredDevices = `-- name: ListDiscoveredDevices :many
SELECT id, discovery_profile_id, ip_address, port, status, created_at, updated_at FROM discovered_devices
WHERE discovery_profile_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDiscoveredDevices(ctx context.Context, discoveryProfileID pgtype.Int8) ([]DiscoveredDevice, error) {
	rows, err := q.db.Query(ctx, listDiscoveredDevices, discoveryProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscoveredDevice
	for rows.Next() {
		var i DiscoveredDevice
		if err := rows.Scan(
			&i.ID,
			&i.DiscoveryProfileID,
			&i.IpAddress,
			&i.Port,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDiscoveredDeviceStatus = `-- name: UpdateDiscoveredDeviceStatus :exec
UPDATE discovered_devices
SET 
    status = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateDiscoveredDeviceStatusParams struct {
	ID     int64       `json:"id"`
	Status pgtype.Text `json:"status"`
}

func (q *Queries) UpdateDiscoveredDeviceStatus(ctx context.Context, arg UpdateDiscoveredDeviceStatusParams) error {
	_, err := q.db.Exec(ctx, updateDiscoveredDeviceStatus, arg.ID, arg.Status)
	return err
}
