// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: discovery_profiles.sql

package dbgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDiscoveryProfile = `-- name: CreateDiscoveryProfile :one
INSERT INTO discovery_profiles (
    name, target_value, ports, port_scan_timeout_ms, credential_profile_ids, auto_provision
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, name, target_value, ports, port_scan_timeout_ms, credential_profile_ids, last_run_at, last_run_status, devices_discovered, created_at, updated_at, deleted_at, auto_provision
`

type CreateDiscoveryProfileParams struct {
	Name                 string          `json:"name"`
	TargetValue          string          `json:"target_value"`
	Ports                json.RawMessage `json:"ports"`
	PortScanTimeoutMs    pgtype.Int4     `json:"port_scan_timeout_ms"`
	CredentialProfileIds json.RawMessage `json:"credential_profile_ids"`
	AutoProvision        pgtype.Bool     `json:"auto_provision"`
}

func (q *Queries) CreateDiscoveryProfile(ctx context.Context, arg CreateDiscoveryProfileParams) (DiscoveryProfile, error) {
	row := q.db.QueryRow(ctx, createDiscoveryProfile,
		arg.Name,
		arg.TargetValue,
		arg.Ports,
		arg.PortScanTimeoutMs,
		arg.CredentialProfileIds,
		arg.AutoProvision,
	)
	var i DiscoveryProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TargetValue,
		&i.Ports,
		&i.PortScanTimeoutMs,
		&i.CredentialProfileIds,
		&i.LastRunAt,
		&i.LastRunStatus,
		&i.DevicesDiscovered,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AutoProvision,
	)
	return i, err
}

const deleteDiscoveryProfile = `-- name: DeleteDiscoveryProfile :exec
UPDATE discovery_profiles
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteDiscoveryProfile(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDiscoveryProfile, id)
	return err
}

const getDiscoveryProfile = `-- name: GetDiscoveryProfile :one
SELECT id, name, target_value, ports, port_scan_timeout_ms, credential_profile_ids, last_run_at, last_run_status, devices_discovered, created_at, updated_at, deleted_at, auto_provision FROM discovery_profiles
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetDiscoveryProfile(ctx context.Context, id uuid.UUID) (DiscoveryProfile, error) {
	row := q.db.QueryRow(ctx, getDiscoveryProfile, id)
	var i DiscoveryProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TargetValue,
		&i.Ports,
		&i.PortScanTimeoutMs,
		&i.CredentialProfileIds,
		&i.LastRunAt,
		&i.LastRunStatus,
		&i.DevicesDiscovered,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AutoProvision,
	)
	return i, err
}

const listDiscoveryProfiles = `-- name: ListDiscoveryProfiles :many
SELECT id, name, target_value, ports, port_scan_timeout_ms, credential_profile_ids, last_run_at, last_run_status, devices_discovered, created_at, updated_at, deleted_at, auto_provision FROM discovery_profiles
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListDiscoveryProfiles(ctx context.Context) ([]DiscoveryProfile, error) {
	rows, err := q.db.Query(ctx, listDiscoveryProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscoveryProfile
	for rows.Next() {
		var i DiscoveryProfile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TargetValue,
			&i.Ports,
			&i.PortScanTimeoutMs,
			&i.CredentialProfileIds,
			&i.LastRunAt,
			&i.LastRunStatus,
			&i.DevicesDiscovered,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.AutoProvision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDiscoveryProfile = `-- name: UpdateDiscoveryProfile :one
UPDATE discovery_profiles
SET 
    name = $2,
    target_value = $3,
    ports = $4,
    port_scan_timeout_ms = $5,
    credential_profile_ids = $6,
    auto_provision = $7,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, target_value, ports, port_scan_timeout_ms, credential_profile_ids, last_run_at, last_run_status, devices_discovered, created_at, updated_at, deleted_at, auto_provision
`

type UpdateDiscoveryProfileParams struct {
	ID                   uuid.UUID       `json:"id"`
	Name                 string          `json:"name"`
	TargetValue          string          `json:"target_value"`
	Ports                json.RawMessage `json:"ports"`
	PortScanTimeoutMs    pgtype.Int4     `json:"port_scan_timeout_ms"`
	CredentialProfileIds json.RawMessage `json:"credential_profile_ids"`
	AutoProvision        pgtype.Bool     `json:"auto_provision"`
}

func (q *Queries) UpdateDiscoveryProfile(ctx context.Context, arg UpdateDiscoveryProfileParams) (DiscoveryProfile, error) {
	row := q.db.QueryRow(ctx, updateDiscoveryProfile,
		arg.ID,
		arg.Name,
		arg.TargetValue,
		arg.Ports,
		arg.PortScanTimeoutMs,
		arg.CredentialProfileIds,
		arg.AutoProvision,
	)
	var i DiscoveryProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TargetValue,
		&i.Ports,
		&i.PortScanTimeoutMs,
		&i.CredentialProfileIds,
		&i.LastRunAt,
		&i.LastRunStatus,
		&i.DevicesDiscovered,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AutoProvision,
	)
	return i, err
}

const updateDiscoveryProfileStatus = `-- name: UpdateDiscoveryProfileStatus :exec
UPDATE discovery_profiles
SET 
    last_run_at = NOW(),
    last_run_status = $2,
    devices_discovered = $3,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateDiscoveryProfileStatusParams struct {
	ID                uuid.UUID   `json:"id"`
	LastRunStatus     pgtype.Text `json:"last_run_status"`
	DevicesDiscovered pgtype.Int4 `json:"devices_discovered"`
}

func (q *Queries) UpdateDiscoveryProfileStatus(ctx context.Context, arg UpdateDiscoveryProfileStatusParams) error {
	_, err := q.db.Exec(ctx, updateDiscoveryProfileStatus, arg.ID, arg.LastRunStatus, arg.DevicesDiscovered)
	return err
}
