// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: discoveryProfiles.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDiscoveryProfile = `-- name: CreateDiscoveryProfile :one
INSERT INTO discovery_profiles (
    name, target_value, port, port_scan_timeout_ms, credential_profile_id, auto_provision, auto_run
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, name, target_value, port, port_scan_timeout_ms, credential_profile_id, last_run_at, last_run_status, devices_discovered, created_at, updated_at, auto_provision, auto_run
`

type CreateDiscoveryProfileParams struct {
	Name                string      `json:"name"`
	TargetValue         string      `json:"target_value"`
	Port                int32       `json:"port"`
	PortScanTimeoutMs   pgtype.Int4 `json:"port_scan_timeout_ms"`
	CredentialProfileID int64       `json:"credential_profile_id"`
	AutoProvision       pgtype.Bool `json:"auto_provision"`
	AutoRun             pgtype.Bool `json:"auto_run"`
}

func (q *Queries) CreateDiscoveryProfile(ctx context.Context, arg CreateDiscoveryProfileParams) (DiscoveryProfile, error) {
	row := q.db.QueryRow(ctx, createDiscoveryProfile,
		arg.Name,
		arg.TargetValue,
		arg.Port,
		arg.PortScanTimeoutMs,
		arg.CredentialProfileID,
		arg.AutoProvision,
		arg.AutoRun,
	)
	var i DiscoveryProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TargetValue,
		&i.Port,
		&i.PortScanTimeoutMs,
		&i.CredentialProfileID,
		&i.LastRunAt,
		&i.LastRunStatus,
		&i.DevicesDiscovered,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AutoProvision,
		&i.AutoRun,
	)
	return i, err
}

const deleteDiscoveryProfile = `-- name: DeleteDiscoveryProfile :exec
DELETE FROM discovery_profiles
WHERE id = $1
`

func (q *Queries) DeleteDiscoveryProfile(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteDiscoveryProfile, id)
	return err
}

const getDiscoveryProfile = `-- name: GetDiscoveryProfile :one
SELECT id, name, target_value, port, port_scan_timeout_ms, credential_profile_id, last_run_at, last_run_status, devices_discovered, created_at, updated_at, auto_provision, auto_run FROM discovery_profiles
WHERE id = $1
`

func (q *Queries) GetDiscoveryProfile(ctx context.Context, id int64) (DiscoveryProfile, error) {
	row := q.db.QueryRow(ctx, getDiscoveryProfile, id)
	var i DiscoveryProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TargetValue,
		&i.Port,
		&i.PortScanTimeoutMs,
		&i.CredentialProfileID,
		&i.LastRunAt,
		&i.LastRunStatus,
		&i.DevicesDiscovered,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AutoProvision,
		&i.AutoRun,
	)
	return i, err
}

const listDiscoveryProfiles = `-- name: ListDiscoveryProfiles :many
SELECT id, name, target_value, port, port_scan_timeout_ms, credential_profile_id, last_run_at, last_run_status, devices_discovered, created_at, updated_at, auto_provision, auto_run FROM discovery_profiles
ORDER BY created_at DESC
`

func (q *Queries) ListDiscoveryProfiles(ctx context.Context) ([]DiscoveryProfile, error) {
	rows, err := q.db.Query(ctx, listDiscoveryProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscoveryProfile
	for rows.Next() {
		var i DiscoveryProfile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TargetValue,
			&i.Port,
			&i.PortScanTimeoutMs,
			&i.CredentialProfileID,
			&i.LastRunAt,
			&i.LastRunStatus,
			&i.DevicesDiscovered,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AutoProvision,
			&i.AutoRun,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDiscoveryProfile = `-- name: UpdateDiscoveryProfile :one
UPDATE discovery_profiles
SET 
    name = $2,
    target_value = $3,
    port = $4,
    port_scan_timeout_ms = $5,
    credential_profile_id = $6,
    auto_provision = $7,
    auto_run = $8,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, target_value, port, port_scan_timeout_ms, credential_profile_id, last_run_at, last_run_status, devices_discovered, created_at, updated_at, auto_provision, auto_run
`

type UpdateDiscoveryProfileParams struct {
	ID                  int64       `json:"id"`
	Name                string      `json:"name"`
	TargetValue         string      `json:"target_value"`
	Port                int32       `json:"port"`
	PortScanTimeoutMs   pgtype.Int4 `json:"port_scan_timeout_ms"`
	CredentialProfileID int64       `json:"credential_profile_id"`
	AutoProvision       pgtype.Bool `json:"auto_provision"`
	AutoRun             pgtype.Bool `json:"auto_run"`
}

func (q *Queries) UpdateDiscoveryProfile(ctx context.Context, arg UpdateDiscoveryProfileParams) (DiscoveryProfile, error) {
	row := q.db.QueryRow(ctx, updateDiscoveryProfile,
		arg.ID,
		arg.Name,
		arg.TargetValue,
		arg.Port,
		arg.PortScanTimeoutMs,
		arg.CredentialProfileID,
		arg.AutoProvision,
		arg.AutoRun,
	)
	var i DiscoveryProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TargetValue,
		&i.Port,
		&i.PortScanTimeoutMs,
		&i.CredentialProfileID,
		&i.LastRunAt,
		&i.LastRunStatus,
		&i.DevicesDiscovered,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AutoProvision,
		&i.AutoRun,
	)
	return i, err
}

const updateDiscoveryProfileStatus = `-- name: UpdateDiscoveryProfileStatus :exec
UPDATE discovery_profiles
SET 
    last_run_at = NOW(),
    last_run_status = $2,
    devices_discovered = $3,
    updated_at = NOW()
WHERE id = $1
`

type UpdateDiscoveryProfileStatusParams struct {
	ID                int64       `json:"id"`
	LastRunStatus     pgtype.Text `json:"last_run_status"`
	DevicesDiscovered pgtype.Int4 `json:"devices_discovered"`
}

func (q *Queries) UpdateDiscoveryProfileStatus(ctx context.Context, arg UpdateDiscoveryProfileStatusParams) error {
	_, err := q.db.Exec(ctx, updateDiscoveryProfileStatus, arg.ID, arg.LastRunStatus, arg.DevicesDiscovered)
	return err
}
