// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"encoding/json"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CredentialProfile struct {
	ID             uuid.UUID          `json:"id"`
	Name           string             `json:"name"`
	Description    pgtype.Text        `json:"description"`
	Protocol       string             `json:"protocol"`
	CredentialData json.RawMessage    `json:"credential_data"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type DiscoveredDevice struct {
	ID                 uuid.UUID          `json:"id"`
	DiscoveryProfileID uuid.NullUUID      `json:"discovery_profile_id"`
	IpAddress          netip.Addr         `json:"ip_address"`
	Port               int32              `json:"port"`
	Status             pgtype.Text        `json:"status"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type DiscoveryProfile struct {
	ID                   uuid.UUID          `json:"id"`
	Name                 string             `json:"name"`
	TargetValue          string             `json:"target_value"`
	Ports                json.RawMessage    `json:"ports"`
	PortScanTimeoutMs    pgtype.Int4        `json:"port_scan_timeout_ms"`
	CredentialProfileIds json.RawMessage    `json:"credential_profile_ids"`
	LastRunAt            pgtype.Timestamptz `json:"last_run_at"`
	LastRunStatus        pgtype.Text        `json:"last_run_status"`
	DevicesDiscovered    pgtype.Int4        `json:"devices_discovered"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
	AutoProvision        pgtype.Bool        `json:"auto_provision"`
}

type Metric struct {
	Timestamp   pgtype.Timestamptz `json:"timestamp"`
	MetricGroup string             `json:"metric_group"`
	DeviceID    uuid.UUID          `json:"device_id"`
	Tags        json.RawMessage    `json:"tags"`
	ValUsed     pgtype.Float8      `json:"val_used"`
	ValTotal    pgtype.Float8      `json:"val_total"`
}

type Monitor struct {
	ID                     uuid.UUID          `json:"id"`
	DisplayName            pgtype.Text        `json:"display_name"`
	Hostname               pgtype.Text        `json:"hostname"`
	IpAddress              netip.Addr         `json:"ip_address"`
	PluginID               string             `json:"plugin_id"`
	CredentialProfileID    uuid.UUID          `json:"credential_profile_id"`
	DiscoveryProfileID     uuid.UUID          `json:"discovery_profile_id"`
	PollingIntervalSeconds pgtype.Int4        `json:"polling_interval_seconds"`
	Status                 pgtype.Text        `json:"status"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	DeletedAt              pgtype.Timestamptz `json:"deleted_at"`
	Port                   pgtype.Int4        `json:"port"`
}
