// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"encoding/json"
	"net/netip"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type CredentialProfile struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Protocol    string             `json:"protocol"`
	Payload     json.RawMessage    `json:"payload"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type DiscoveredDevice struct {
	ID                 int64              `json:"id"`
	DiscoveryProfileID pgtype.Int8        `json:"discovery_profile_id"`
	IpAddress          netip.Addr         `json:"ip_address"`
	Port               int32              `json:"port"`
	Status             pgtype.Text        `json:"status"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type DiscoveryProfile struct {
	ID                  int64              `json:"id"`
	Name                string             `json:"name"`
	TargetValue         string             `json:"target_value"`
	Port                int32              `json:"port"`
	PortScanTimeoutMs   pgtype.Int4        `json:"port_scan_timeout_ms"`
	CredentialProfileID int64              `json:"credential_profile_id"`
	LastRunAt           pgtype.Timestamptz `json:"last_run_at"`
	LastRunStatus       pgtype.Text        `json:"last_run_status"`
	DevicesDiscovered   pgtype.Int4        `json:"devices_discovered"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	AutoProvision       pgtype.Bool        `json:"auto_provision"`
	AutoRun             pgtype.Bool        `json:"auto_run"`
}

type Metric struct {
	Timestamp time.Time   `json:"timestamp"`
	DeviceID  int64       `json:"device_id"`
	Name      string      `json:"name"`
	Value     float64     `json:"value"`
	Type      pgtype.Text `json:"type"`
}

type Monitor struct {
	ID                     int64              `json:"id"`
	DisplayName            pgtype.Text        `json:"display_name"`
	Hostname               pgtype.Text        `json:"hostname"`
	IpAddress              netip.Addr         `json:"ip_address"`
	PluginID               string             `json:"plugin_id"`
	CredentialProfileID    int64              `json:"credential_profile_id"`
	DiscoveryProfileID     int64              `json:"discovery_profile_id"`
	PollingIntervalSeconds pgtype.Int4        `json:"polling_interval_seconds"`
	Status                 pgtype.Text        `json:"status"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	Port                   pgtype.Int4        `json:"port"`
}
