// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ClearDiscoveredDevices(ctx context.Context, discoveryProfileID uuid.NullUUID) error
	CreateCredentialProfile(ctx context.Context, arg CreateCredentialProfileParams) (CredentialProfile, error)
	CreateDiscoveredDevice(ctx context.Context, arg CreateDiscoveredDeviceParams) (DiscoveredDevice, error)
	CreateDiscoveryProfile(ctx context.Context, arg CreateDiscoveryProfileParams) (DiscoveryProfile, error)
	CreateMonitor(ctx context.Context, arg CreateMonitorParams) (Monitor, error)
	DeleteCredentialProfile(ctx context.Context, id uuid.UUID) error
	DeleteDiscoveredDevice(ctx context.Context, id uuid.UUID) error
	DeleteDiscoveryProfile(ctx context.Context, id uuid.UUID) error
	DeleteMonitor(ctx context.Context, id uuid.UUID) error
	// Get all unique metric names (for discovery/autocomplete)
	GetAllMetricNames(ctx context.Context, deviceIds []uuid.UUID) ([]string, error)
	GetCredentialProfile(ctx context.Context, id uuid.UUID) (CredentialProfile, error)
	GetDiscoveredDevice(ctx context.Context, id uuid.UUID) (DiscoveredDevice, error)
	GetDiscoveryProfile(ctx context.Context, id uuid.UUID) (DiscoveryProfile, error)
	// Returns only monitor IDs that exist and are not soft-deleted.
	// Used to validate a batch of IDs before metrics queries.
	GetExistingMonitorIDs(ctx context.Context, monitorIds []uuid.UUID) ([]uuid.UUID, error)
	// Query the latest value for each metric (per device) with prefix matching
	GetLatestMetricsByDeviceAndPrefix(ctx context.Context, arg GetLatestMetricsByDeviceAndPrefixParams) ([]Metric, error)
	// Query metrics for devices with per-metric limiting using LATERAL JOIN
	// Returns top N rows per (device_id, metric_name) group ordered by timestamp DESC
	GetMetricsByDeviceAndPrefix(ctx context.Context, arg GetMetricsByDeviceAndPrefixParams) ([]Metric, error)
	GetMonitor(ctx context.Context, id uuid.UUID) (Monitor, error)
	// Fetches a single monitor with its credential data.
	// Used for efficient cache invalidation.
	GetMonitorWithCredentials(ctx context.Context, id uuid.UUID) (GetMonitorWithCredentialsRow, error)
	GetMonitorsByCredentialID(ctx context.Context, credentialProfileID uuid.UUID) ([]uuid.UUID, error)
	// Fetches all monitors using a specific credential profile, with their credential data.
	// Used for efficient cache invalidation when a credential profile changes.
	GetMonitorsWithCredentialsByCredentialID(ctx context.Context, credentialProfileID uuid.UUID) ([]GetMonitorsWithCredentialsByCredentialIDRow, error)
	// Loads active monitors with their credential data in a single query.
	// Used by scheduler to initialize cache at startup.
	ListActiveMonitorsWithCredentials(ctx context.Context) ([]ListActiveMonitorsWithCredentialsRow, error)
	ListAllDiscoveredDevices(ctx context.Context) ([]DiscoveredDevice, error)
	ListCredentialProfiles(ctx context.Context) ([]CredentialProfile, error)
	ListDiscoveredDevices(ctx context.Context, discoveryProfileID uuid.NullUUID) ([]DiscoveredDevice, error)
	ListDiscoveryProfiles(ctx context.Context) ([]DiscoveryProfile, error)
	ListMonitors(ctx context.Context) ([]Monitor, error)
	UpdateCredentialProfile(ctx context.Context, arg UpdateCredentialProfileParams) (CredentialProfile, error)
	UpdateDiscoveredDeviceStatus(ctx context.Context, arg UpdateDiscoveredDeviceStatusParams) error
	UpdateDiscoveryProfile(ctx context.Context, arg UpdateDiscoveryProfileParams) (DiscoveryProfile, error)
	UpdateDiscoveryProfileStatus(ctx context.Context, arg UpdateDiscoveryProfileStatusParams) error
	UpdateMonitor(ctx context.Context, arg UpdateMonitorParams) (Monitor, error)
	// Updates monitor status (active/down) and updated_at timestamp.
	UpdateMonitorStatus(ctx context.Context, arg UpdateMonitorStatusParams) error
}

var _ Querier = (*Queries)(nil)
